### ISSUE TITLE
The way to download Volve data

### ISSUE THREAD

**Issue by dhhien1503** [DeepWave-KAUST/Seis2Rock#1]
Hi Miguel,

Thank you for the valuable tool Seis2Rock. I'd like to ask for the Volve data that I tried to download this from the website of Equinor but I can not get the weblink for that. 

Could you please kindly open the link for me to download this dataset then I could learn from this after that if possible I can apply to our field data set which will be create for us.

Thank you very much for your kind support.
Hien

**Comment by miguelcorralesg** [comment]
Hi Hein,

Thanks for your message, and for using Seis2Rock. I wanted to comment on the Volve data quickly. It is open access, thanks to Equinor, and includes prestack data in offsets. You can download it here: https://www.equinor.com/energy/volve-data-sharing

We have preprocessed this data to convert it from offsets to angle gathers using the velocity model. More details about this preprocessing can be found in our article, specifically in section 3.2.1 Preprocessing of the Volve Data: https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2023EA003301 

Please note that these notebooks do not include the preprocessing steps. However, if you want to convert your data from offset to angle domain, you can follow this example: https://github.com/PyLops/pylops_notebooks/blob/master/developement/PreStackInversion-Volve.ipynb

The small sections/preprocessed data used for the Volve notebooks is available now in zenodo: https://zenodo.org/records/11481946
